# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0002_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='format',
            field=models.CharField(default='', max_length=5),
        ),
    ]
