# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0003_image_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='format',
        ),
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
    ]
